### PR TITLE
feat: add `no_dispatch` to `dask_method`

### PR DESCRIPTION
**Pull request by agoose77**

### CODE REVIEW

**Comment by agoose77** [comment]
@lgray give this a spin and let us know!

**Comment by lgray** [comment]
Looks good from my side - please merge!

**Comment by lgray** [comment]
A release would be appreciated as well.

**Comment by douglasdavis** [comment]
Looks like this is a good to go in?

**Comment by lgray** [comment]
yes, please!

**Comment by douglasdavis** [comment]
Cool- 2023.12.0 on PyPI momentarily

**Pull request merged**
