### PR TITLE
Modify workaround for touching `what` in dak.with_name

### LINKED ISSUE #223: Fields added by `dak.with_field` cannot be optimized away
Not much more to say than in the title.

```python3
import uproot
import dask_awkward as dak

x = uproot.dask({"https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/nano_dy.root?raw=true": "Events"})
x["something_silly"] = x.Muon_looseId
print(dak.necessary_columns(x.Muon_pt))
```

prints out:
```
{'from-uproot-ffd643ed3e3f19249385270346179fbb': ['Muon_looseId', 'Muon_pt']}
```

and should print out:
```
{'from-uproot-ffd643ed3e3f19249385270346179fbb': ['Muon_pt']}
```

### PR DESCRIPTION
**Pull request by lgray**
This can be relaxed now but is still a consequence of #223.

### CODE REVIEW

**Comment by lgray** [comment]
Do not merge until https://github.com/scikit-hep/awkward/pull/2395 is merged!

**Comment by martindurant** [comment]
We should be able to make a test showing that necessary_columns does the right thing, no?

**Comment by lgray** [comment]
Yes - but it seems this is also a partial fix (since 2395 is a partial fix). Working out the edge cases.

**Comment by lgray** [comment]
@agoose77 FYI - the partial fix is indeed partial. It's a bit strange that I need to touch some of these, at least I can relax the over-aggressive touching.

**Comment by lgray** [comment]
So digging a bit deeper this change appears to be a consequence `with_field` always spawning a `map_partitions` which means the data in `what` must be read and attached to the array (so we *must* touch `what` but we don't need to touch anything below what unless it's specifically called for). 

The behavior at the type tracer level seems reasonable:
```python3
muon = ttarray.muon
print("muon: ", report.data_touched)
muon["weight"] = ttarray.weight
print("assign:", report.data_touched)
``` 
yields:
```
muon:  []
assign: ['muon_list_outer!']
```

Which is correct behavior since that never accesses `weight`. similarly, in the more complex test the equivalent of `weight` is assigned but never accessed.

So, actually, instead of anything to do with fixing #223 it is an example of it. Since the typetracer is doing the right thing and we are only running into this because we do not cull un-used columns that are attached by `with_field`.

**Comment by lgray** [comment]
Please merge this one when awkward pushes its next release as the associated fix is now in main.

**Pull request merged**
