### PR TITLE
fix: make ak.singletons workaround operate correctly in all cases

### PR DESCRIPTION
**Pull request by lgray**
Present implementation of singletons was failing column optimization when passed RecordArrays that were then accessed later.

### CODE REVIEW

**Comment by martindurant** [comment]
Will look shortly. Would appreciate a test case showing the previous failure now fixed.

**Comment by lgray** [comment]
I'll see if I can boil it down. It popped up in a reasonably complex analysis query, it can take some time.

**Comment by lgray** [comment]
@martindurant I couldn't get it to outright fail but I got it to cause the column optimization failure which eventually causes the failure in a more complex query. 

I made it so that test fails if a warning is emitted, which emulates the outcome in the more complex case. 

The test fails with previous impl and passes now, good enough?

**Comment by martindurant** [comment]
Yes, that's reasonable.

**Comment by martindurant** [comment]
Maybe we should keep a list in an issue of these "will remove workaround" situations.
Will merge when green.

**Pull request merged**
