### PR TITLE
feat: add support for `Delayed` in partitionwise layer creation.

### PR DESCRIPTION
**Pull request by douglasdavis**
Broadcasting will occur equivalently at each partition because the Delayed object is *not* partitioned (as shown in the test added in this PR).

### CODE REVIEW

**Comment by lgray** [comment]
Cool, I'll give it a try in the morning!

**Comment by lgray** [comment]
I'm getting an odd error when I try to print out the dask awkward array that's made from something using delayed:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/coffea-dev/coffea/tests/test_lookup_tools.py", line 177, in test_correctionlib
    print(test_out_dak)
  File "/Users/lgray/coffea-dev/dask-awkward/src/dask_awkward/lib/core.py", line 998, in __str__
    f"npartitions={self.npartitions}"
  File "/Users/lgray/coffea-dev/dask-awkward/src/dask_awkward/lib/core.py", line 1083, in npartitions
    return len(self.divisions) - 1
  File "/Users/lgray/miniforge3/envs/ewkcoffea-debug/lib/python3.10/site-packages/dask/delayed.py", line 635, in __len__
    raise TypeError("Delayed objects of unspecified length have no len()")
TypeError: Delayed objects of unspecified length have no len()
```

I haven't traced it to understand why the output dak array things it's a dask.delayed?

**Comment by agoose77** [comment]
It's probably that something's constructed `Array` with the `divisions` argument taken from `delayed.divisions`, i.e. in a previous frame.

**Comment by douglasdavis** [comment]
Is it possible to get a repro for that `TypeError`?

`divisions` should always be a tuple (specifically `tuple[int, ...] | tuple[None, ...]`) on a `dak.Array`

**Comment by lgray** [comment]
I'll see if I can get one - I'm trying to make sure first I'm not bamboozling myself.

**Comment by lgray** [comment]
somehow array.divisions has, itself, become a delayed object!?

**Comment by douglasdavis** [comment]
Just to jot this down information down in a more permanent place: we discovered during slack conversation that if a `Delayed` object was the first thing passed to `map_partitions`, we broke an assumption in the code that the first argument would be a `dak.Array`. The `map_partitions` implementation is not invariant w.r.t. order of function arguments, but at least one `dak.Array` is required.

**Comment by martindurant** [comment]
> we broke an assumption in the code that the first argument would be a dak.Array

easy to fix, right?

**Pull request merged**
