### PR TITLE
feat: turn off ak's typetracer _new checks during optimize

### PR DESCRIPTION
**Pull request by martindurant**
Will have no effect until https://github.com/scikit-hep/awkward/pull/3054 is out

@lgray , any other places we need this optimisation?

### CODE REVIEW

**Comment by lgray** [comment]
During `dak.necessary_columns` as well. Though that has some slowness that's kind of strange but different, it hasn't been high priority. This will help, of course.

**Comment by jpivarski** [comment]
If you specify the lines of code that should be avoided, I'll add them to this PR (with only one global switch for all).

**Comment by lgray** [comment]
Yeah I haven't fully thought through or experienced the user-side lifecycle of `necessary_columns`... I have no idea if people use it a lot directly and if it needs to be snappy.

**Comment by martindurant** [comment]
OK, will merge this now, and we can add more blocks or set a global state in the future, if we decide.

**Pull request merged**
